/**
 * All user-facing text lives here (ready for future localisation).
 * Use functions for strings with parameters.
 */
export const STRINGS = {
  titleTop: 'BITRIX24',
  titleBottom: 'PARTNER FIGHTER',
  /** iPhone (no fullscreen for pages): how to install the game for a fullscreen app. */
  iosFullscreenHint:
    'Tela cheia no iPhone: toque em Compartilhar e depois em “Adicionar à Tela de Início”',
  /** Boot loading screen label (progress from 0 to 1). */
  loading: (progress: number) =>
    `CARREGANDO  ${Math.round(Math.min(Math.max(progress, 0), 1) * 100)}%`,
  play: 'JOGAR',
  modeStory: 'HISTÓRIA',
  modeQuickFight: 'LUTA RÁPIDA',
  modeGallery: 'GALERIA',
  galleryTitle: 'GALERIA DE FINAIS',
  galleryCount: (unlocked: number, total: number) => `${unlocked}/${total} LIBERADOS`,
  galleryLocked: 'BLOQUEADO',
  galleryLockedHint: (name: string) => `Zere o Modo História com ${name} para liberar`,
  galleryOpenHint: (name: string) => `ENTER ou toque para ver o final de ${name}`,
  galleryAllUnlocked: 'TODOS OS FINAIS LIBERADOS!',
  galleryNoArt: (name: string) => `Final de ${name} liberado: ilustração em breve`,
  galleryHint: '← → ↑ ↓ escolher    ENTER ver final    ESC voltar',
  galleryViewerHint: '← → outro final    ESC ou toque para voltar',
  /** Complete gallery: the hidden fighters it unlocks (e.g. the final boss). */
  galleryReward: (names: string) => `${names} LIBERADO NA LUTA RÁPIDA!`,
  galleryRewardTeaser: 'Libere todos os finais para desbloquear um lutador secreto',
  /** Campaign ending: this fighter's ending just went into the gallery. */
  galleryNewUnlock: (unlocked: number, total: number) =>
    `NOVO FINAL NA GALERIA  ${unlocked}/${total}`,
  modeHint: '← → escolher    ENTER confirmar    ESC voltar',
  storySelectTitle: 'MODO HISTÓRIA',
  storyOrigin: (label: string) => `ORIGEM  ${label}`,
  /** Story select badge: where the chosen fighter's campaign starts. */
  storyStart: (label: string) => `PARTIDA  ${label}`,
  storyStartingPoint: 'PONTO DE PARTIDA',
  storyLockedRival: 'RIVAL',
  storyLockedSoon: 'EM BREVE',
  storyTrip: (from: string, to: string) => `${from}  →  ${to}`,
  storyLeg: (current: number, total: number) => `ETAPA ${current}/${total}`,
  storyNextDestination: 'PRÓXIMO DESTINO',
  storyNextChallenge: 'PRÓXIMO DESAFIO',
  storyFinalBoss: 'FINAL BOSS',
  storyContinue: 'CONTINUAR',
  storyRetry: 'TENTAR NOVAMENTE',
  storyQuit: 'SAIR PARA O MENU',
  storyPlayAgain: 'JOGAR NOVAMENTE',
  storyMapHint: 'ENTER ou toque para continuar',
  campaignComplete: 'CAMPANHA CONCLUÍDA',
  campaignCheer: 'BRASIL DOMINADO!',
  campaignCheerWorld: 'MUNDO DOMINADO!',
  campaignRoute: (cities: readonly string[]) => cities.join(' → '),
  confirm: 'CONFIRMAR',
  pressStart: 'PRESSIONE ENTER OU TOQUE',
  /** Under the title's START button (as in the approved art). */
  titleHint: 'PRESSIONE START OU TOQUE',
  version: 'v0.1 - protótipo',
  disclaimer: 'Projeto de fã. Arte e personagens provisórios.',
  previousFighter: '◀',
  nextFighter: '▶',
  selectTitle: 'ESCOLHA SEU PARCEIRO',
  selectHint: '← → ↑ ↓ lutador    Q E dificuldade    ENTER selecionar    ESC voltar',
  selectButton: 'SELECIONAR',
  selectOpponent: (name: string) => `VS  ${name}`,
  /** Quick fight is three steps: your fighter, the rival, the stage. */
  selectStep: (step: number, total: number) => `PASSO ${step} DE ${total}`,
  selectRivalTitle: 'ESCOLHA O RIVAL',
  selectRivalHint: (player: string) =>
    `P1: ${player}    ← → ↑ ↓ rival    Q E dificuldade    ENTER selecionar    ESC voltar`,
  stageSelectTitle: 'ESCOLHA A FASE',
  stageSelectHint: '↑ ↓ ← → fase    ENTER lutar    ESC voltar',
  stageSelectMatch: (player: string, cpu: string) => `${player}  VS  ${cpu}`,
  stageSelectButton: 'LUTAR!',
  back: 'VOLTAR',
  playerOneTag: 'P1',
  comingSoon: 'EM BREVE',
  lockedSlot: '?',
  selectPage: (page: number, total: number) => `${page}/${total}`,
  statPower: 'PODER',
  statSpeed: 'VELOCIDADE',
  statReach: 'ALCANCE',
  difficultyLabel: 'DIFICULDADE',
  difficultyNames: { easy: 'FÁCIL', normal: 'NORMAL', hard: 'DIFÍCIL' },
  previousDifficulty: '<',
  nextDifficulty: '>',
  vsSkipHint: 'ENTER ou toque para pular',
  cpuOnly: 'CPU',
  versus: 'VS',
  round: (n: number) => `ROUND ${n}`,
  finalRound: 'FINAL ROUND',
  roundDraw: 'DRAW',
  matchScore: (left: number, right: number) => `${left} x ${right}`,
  reasonMatchDraw: 'Partida empatada no limite de rounds',
  fight: 'FIGHT!',
  ko: 'K.O.',
  perfect: 'PERFECT',
  timeOver: 'TIME OVER',
  draw: 'EMPATE',
  drawNames: (left: string, right: string) => `${left}  x  ${right}`,
  resultSeparator: '■',
  wins: (name: string) => `${name} VENCEU!`,
  youWin: 'VOCÊ VENCEU!',
  youLose: 'VOCÊ PERDEU',
  reasonKo: 'Vitória por nocaute',
  reasonTimeout: 'Vitória por tempo',
  backToMenu: 'VOLTAR AO MENU',
  rematch: 'REVANCHE',
  newFight: 'NOVA LUTA',
  touchPunch: 'SOCO',
  touchKick: 'CHUTE',
  touchBlock: 'DEF',
  touchSpecial: 'ESP',
  specialMeter: (value: number) => `ESP ${value}/100`,
  specialReady: 'PRONTO',
  special24Zap: '24ZAP COMBO',
  special24ZapEffect: '24ZAP!',
  specialMindhubAgent: 'MINDHUB AGENT',
  specialAlaioVibecode: 'ALAIO VIBECODE!',
  specialGptMaker: 'GPTMAKER!',
  specialFluidz: 'FLUIDZ!',
  specialAlaioStrike: 'ALAIO STRIKE!',
  specialN8n: 'N8N!',
  specialPolice: 'CHAMA O 190!',
  debugHint: 'F2: hitboxes',
  /** Fixed controls bar at the bottom of the fight (keyboard players). */
  fightControlsHint:
    '← → andar    ↑ pular    ↓ agachar    A soco    S chute    D defesa    F especial    ESC pausa',
  pauseTitle: 'PAUSA',
  pauseResume: 'CONTINUAR',
  pauseRestart: 'REINICIAR LUTA',
  pauseQuit: 'SAIR PARA O MENU',
  pauseHint: '↑ ↓ escolher    ENTER confirmar    ESC continuar',
  /** Touch pause button (two bars). */
  touchPause: 'II',
} as const;
