/**
 * All user-facing text lives here (ready for future localisation).
 * Use functions for strings with parameters.
 */
export const STRINGS = {
  titleTop: 'BITRIX24',
  titleBottom: 'PARTNER FIGHTER',
  play: 'JOGAR',
  modeStory: 'HISTÓRIA',
  modeQuickFight: 'LUTA RÁPIDA',
  modeHint: '← → escolher    ENTER confirmar    ESC voltar',
  storySelectTitle: 'MODO HISTÓRIA',
  storyOrigin: (label: string) => `ORIGEM  ${label}`,
  /** Story select badge: where the chosen fighter's campaign starts. */
  storyStart: (label: string) => `PARTIDA  ${label}`,
  storyStartingPoint: 'PONTO DE PARTIDA',
  storyLockedRival: 'RIVAL',
  storyLockedSoon: 'EM BREVE',
  storyTrip: (from: string, to: string) => `${from}  →  ${to}`,
  storyLeg: (current: number, total: number) => `ETAPA ${current}/${total}`,
  storyNextDestination: 'PRÓXIMO DESTINO',
  storyNextChallenge: 'PRÓXIMO DESAFIO',
  storyContinue: 'CONTINUAR',
  storyRetry: 'TENTAR NOVAMENTE',
  storyQuit: 'SAIR PARA O MENU',
  storyPlayAgain: 'JOGAR NOVAMENTE',
  storyMapHint: 'ENTER ou toque para continuar',
  campaignComplete: 'CAMPANHA CONCLUÍDA',
  campaignCheer: 'BRASIL DOMINADO!',
  campaignCheerWorld: 'MUNDO DOMINADO!',
  campaignRoute: (cities: readonly string[]) => cities.join('  →  '),
  confirm: 'CONFIRMAR',
  pressStart: 'PRESSIONE ENTER OU TOQUE',
  /** Under the title's START button (as in the approved art). */
  titleHint: 'PRESSIONE START OU TOQUE',
  version: 'v0.1 - protótipo',
  disclaimer: 'Projeto de fã. Arte e personagens provisórios.',
  previousFighter: '◀',
  nextFighter: '▶',
  selectTitle: 'ESCOLHA SEU PARCEIRO',
  selectHint: '← → lutador    ↑ ↓ dificuldade    ENTER selecionar    ESC voltar',
  selectButton: 'SELECIONAR',
  selectOpponent: (name: string) => `VS  ${name}`,
  back: 'VOLTAR',
  playerOneTag: 'P1',
  comingSoon: 'EM BREVE',
  lockedSlot: '?',
  selectPage: (page: number, total: number) => `${page}/${total}`,
  statPower: 'PODER',
  statSpeed: 'VELOCIDADE',
  statReach: 'ALCANCE',
  difficultyLabel: 'DIFICULDADE',
  difficultyNames: { easy: 'FÁCIL', normal: 'NORMAL', hard: 'DIFÍCIL' },
  previousDifficulty: '<',
  nextDifficulty: '>',
  vsSkipHint: 'ENTER ou toque para pular',
  cpuOnly: 'CPU',
  versus: 'VS',
  round: (n: number) => `ROUND ${n}`,
  finalRound: 'FINAL ROUND',
  roundDraw: 'DRAW',
  matchScore: (left: number, right: number) => `${left} x ${right}`,
  reasonMatchDraw: 'Partida empatada no limite de rounds',
  fight: 'FIGHT!',
  ko: 'K.O.',
  perfect: 'PERFECT',
  timeOver: 'TIME OVER',
  draw: 'EMPATE',
  drawNames: (left: string, right: string) => `${left}  x  ${right}`,
  resultSeparator: '■',
  wins: (name: string) => `${name} VENCEU!`,
  youWin: 'VOCÊ VENCEU!',
  youLose: 'VOCÊ PERDEU',
  reasonKo: 'Vitória por nocaute',
  reasonTimeout: 'Vitória por tempo',
  backToMenu: 'VOLTAR AO MENU',
  touchPunch: 'SOCO',
  touchKick: 'CHUTE',
  touchBlock: 'DEF',
  touchSpecial: 'ESP',
  specialMeter: (value: number) => `ESP ${value}/100`,
  specialReady: 'PRONTO',
  special24Zap: '24ZAP COMBO',
  special24ZapEffect: '24ZAP!',
  specialMindhubAgent: 'MINDHUB AGENT',
  specialAlaioVibecode: 'ALAIO VIBECODE!',
  specialGptMaker: 'GPTMAKER!',
  debugHint: 'F2: hitboxes',
} as const;
