/**
 * All user-facing text lives here (ready for future localisation).
 * Use functions for strings with parameters.
 */
export const STRINGS = {
  titleTop: 'BITRIX24',
  titleBottom: 'PARTNER FIGHTER',
  play: 'JOGAR',
  confirm: 'CONFIRMAR',
  pressStart: 'PRESSIONE ENTER OU TOQUE',
  version: 'v0.1 - protótipo',
  disclaimer: 'Projeto de fã. Arte e personagens provisórios.',
  previousFighter: '◀',
  nextFighter: '▶',
  selectTitle: 'ESCOLHA SEU PARCEIRO',
  selectHint: '← → lutador    ↑ ↓ dificuldade    ENTER selecionar    ESC voltar',
  selectButton: 'SELECIONAR',
  selectOpponent: (name: string) => `VS  ${name}`,
  back: 'VOLTAR',
  playerOneTag: 'P1',
  comingSoon: 'EM BREVE',
  lockedSlot: '?',
  selectPage: (page: number, total: number) => `${page}/${total}`,
  statPower: 'PODER',
  statSpeed: 'VELOCIDADE',
  statReach: 'ALCANCE',
  difficultyLabel: 'DIFICULDADE',
  difficultyNames: { easy: 'FÁCIL', normal: 'NORMAL', hard: 'DIFÍCIL' },
  previousDifficulty: '<',
  nextDifficulty: '>',
  vsSkipHint: 'ENTER ou toque para pular',
  cpuOnly: 'CPU',
  versus: 'VS',
  round: (n: number) => `ROUND ${n}`,
  finalRound: 'FINAL ROUND',
  roundDraw: 'DRAW',
  matchScore: (left: number, right: number) => `${left} x ${right}`,
  reasonMatchDraw: 'Partida empatada no limite de rounds',
  fight: 'FIGHT!',
  ko: 'K.O.',
  timeOver: 'TIME OVER',
  draw: 'EMPATE',
  drawNames: (left: string, right: string) => `${left}  x  ${right}`,
  resultSeparator: '■',
  wins: (name: string) => `${name} VENCEU!`,
  youWin: 'VOCÊ VENCEU!',
  youLose: 'VOCÊ PERDEU',
  reasonKo: 'Vitória por nocaute',
  reasonTimeout: 'Vitória por tempo',
  backToMenu: 'VOLTAR AO MENU',
  touchPunch: 'SOCO',
  touchKick: 'CHUTE',
  touchBlock: 'DEF',
  touchSpecial: 'ESP',
  specialMeter: (value: number) => `ESP ${value}/100`,
  specialReady: 'PRONTO',
  special24Zap: '24ZAP COMBO',
  special24ZapEffect: '24ZAP!',
  specialMindhubAgent: 'MINDHUB AGENT',
  debugHint: 'F2: hitboxes',
} as const;
