import { STRINGS } from '../config/strings';
import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/**
 * AISLAN - ZOPU. Balanced: medium mobility, damage and recovery, using the standard body, and
 * the purple liquid special FLUIDZ!.
 */
export const aislan: FighterConfig = {
  id: 'aislan',
  name: 'aislan',
  displayName: 'AISLAN',
  description: 'ZOPU',
  playable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.1,
    backWalkSpeed: 2.5,
    jumpForce: 16.5,
    jumpHorizontalSpeed: 3.9,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'aislan.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 7,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 3,
      recoveryFrames: 11,
      hitbox: { x: 24, y: -142, width: 58, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'aislan.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 11,
      chipDamage: 1,
      startupFrames: 10,
      activeFrames: 4,
      recoveryFrames: 17,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    crouchPunch: {
      id: 'aislan.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 5,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 3,
      recoveryFrames: 9,
      hitbox: { x: 22, y: -92, width: 52, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'aislan.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 9,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 18,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    airPunch: {
      id: 'aislan.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 7,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 6,
      recoveryFrames: 10,
      hitbox: { x: 16, y: -118, width: 52, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'aislan.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 10,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 8,
      recoveryFrames: 14,
      hitbox: { x: -12, y: -80, width: 90, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [
    {
      // A gush of purple liquid: a rippling stream with a splash at the end of its reach.
      id: 'aislan.fluidz',
      displayName: STRINGS.specialFluidz,
      state: 'special',
      level: 'mid',
      meterCost: 30,
      groundOnly: true,
      // A small lean into the pour.
      advanceSpeed: 1.5,
      damage: 17,
      chipDamage: 2,
      startupFrames: 13,
      activeFrames: 7,
      // Blocked, it leaves him at a disadvantage (23 recovery against 15 blockstun).
      recoveryFrames: 23,
      // Reach 164 px (his kick: 100), waist to chest.
      hitbox: { x: 24, y: -124, width: 140, height: 62 },
      hitstunFrames: 24,
      blockstunFrames: 15,
      knockback: 8.5,
      blockPushback: 5.5,
      hitstopFrames: 11,
    },
  ],
  palette: { body: 0x164f89, accent: 0xe0b75a, skin: 0xe0ac69, outline: 0x0b0820 },
  assets: {
    portrait: 'fighters/aislan/portrait.png',
    pixelArt: true,
    specialEffects: {
      'aislan.fluidz': {
        style: 'liquidFlow',
        label: STRINGS.specialFluidz,
        emblem: 'vfx/fluidz-emblem.png',
        sound: 'special-fluidz',
      },
    },
    sprite: {
      sheet: {
        key: 'aislan-sheet',
        path: 'fighters/aislan/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // Eight transparent pixels below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        special: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
      },
    },
  },
};
