import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/** Mobile pressure fighter: faster normals trade damage for initiative. */
export const augusto: FighterConfig = {
  id: 'augusto',
  name: 'augusto',
  displayName: 'AUGUSTO',
  description: 'Arrecife Digital',
  selectable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.45,
    backWalkSpeed: 2.85,
    jumpForce: 16.8,
    jumpHorizontalSpeed: 4.2,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'augusto.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 6,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 8,
      hitbox: { x: 24, y: -142, width: 54, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'augusto.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 11,
      chipDamage: 1,
      startupFrames: 10,
      activeFrames: 4,
      recoveryFrames: 16,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    // Crouching attacks (↓ + A / ↓ + S): the fighter stays low and uses the crouching hurtbox.
    crouchPunch: {
      id: 'augusto.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      // Hits the torso (y -92..-70): blockable either way once levels exist, so 'mid'.
      level: 'mid',
      damage: 4,
      chipDamage: 0,
      startupFrames: 3,
      activeFrames: 3,
      recoveryFrames: 6,
      hitbox: { x: 22, y: -92, width: 48, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'augusto.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      // Sweeps the shins, long and low.
      level: 'low',
      damage: 9,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 4,
      recoveryFrames: 18,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    // Air attacks: gravity and jump momentum continue; they end on landing.
    airPunch: {
      id: 'augusto.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 5,
      chipDamage: 0,
      startupFrames: 3,
      activeFrames: 6,
      recoveryFrames: 8,
      // Chest height, medium reach: connects on the way down.
      hitbox: { x: 16, y: -118, width: 50, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'augusto.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 10,
      chipDamage: 1,
      startupFrames: 6,
      activeFrames: 8,
      recoveryFrames: 13,
      // Long, angled down and starting slightly behind the body: hits cross-ups.
      hitbox: { x: -12, y: -80, width: 88, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [],
  palette: { body: 0x191c24, accent: 0x258bff, skin: 0xb8b8b8, outline: 0x080b12 },
  // Neutral mannequin palette; final portrait and sprite will be supplied later.
  assets: {},
};
