import { STRINGS } from '../config/strings';
import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/**
 * A modestly tougher boss: heavier normals paid for with longer recovery, and the boss
 * special ALAIO STRIKE!: lightning over the whole stage that only a guard stops.
 */
export const dmitry: FighterConfig = {
  id: 'dmitry',
  name: 'dmitry',
  displayName: 'DMITRY',
  description: 'Bitrix24 - Final Boss',
  playable: false,
  // The final boss turns playable (quick fights) once every story ending is unlocked.
  unlock: 'all-endings',
  stats: {
    maxHealth: 108,
    walkSpeed: 3.0,
    backWalkSpeed: 2.4,
    jumpForce: 16.5,
    jumpHorizontalSpeed: 3.9,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'dmitry.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 8,
      chipDamage: 0,
      startupFrames: 6,
      activeFrames: 3,
      recoveryFrames: 13,
      hitbox: { x: 24, y: -142, width: 58, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'dmitry.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 12,
      chipDamage: 1,
      startupFrames: 11,
      activeFrames: 4,
      recoveryFrames: 19,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    crouchPunch: {
      id: 'dmitry.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 6,
      chipDamage: 0,
      startupFrames: 6,
      activeFrames: 3,
      recoveryFrames: 11,
      hitbox: { x: 22, y: -92, width: 52, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'dmitry.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 10,
      chipDamage: 1,
      startupFrames: 10,
      activeFrames: 4,
      recoveryFrames: 20,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    airPunch: {
      id: 'dmitry.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 8,
      chipDamage: 0,
      startupFrames: 6,
      activeFrames: 6,
      recoveryFrames: 12,
      hitbox: { x: 16, y: -118, width: 52, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'dmitry.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 11,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 8,
      recoveryFrames: 16,
      hitbox: { x: -12, y: -80, width: 90, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [
    {
      // Final boss special: he raises his fist and lightning falls on the WHOLE stage. Distance
      // or jumping do not save the rival: the hitbox covers the arena from any position and
      // facing (symmetric: x = -width / 2). Only a guard does (mid: standing or crouching); an
      // airborne rival cannot guard, so a jump is caught too.
      id: 'dmitry.alaioStrike',
      displayName: STRINGS.specialAlaioStrike,
      state: 'special',
      level: 'mid',
      meterCost: 50,
      groundOnly: true,
      advanceSpeed: 0,
      damage: 24,
      chipDamage: 4,
      // A long, loud wind-up (the storm rolls in): time to see it coming and guard.
      startupFrames: 24,
      activeFrames: 8,
      // Very punishable when guarded: 34 recovery against 18 blockstun.
      recoveryFrames: 34,
      hitbox: { x: -1600, y: -1000, width: 3200, height: 1000 },
      hitstunFrames: 30,
      blockstunFrames: 18,
      knockback: 7,
      blockPushback: 5,
      hitstopFrames: 16,
    },
  ],
  palette: { body: 0x172e50, accent: 0x6db9eb, skin: 0xedc3a1, outline: 0x0b0820 },
  assets: {
    portrait: 'fighters/dmitry/portrait.png',
    pixelArt: true,
    specialEffects: {
      'dmitry.alaioStrike': {
        style: 'skyLightning',
        label: STRINGS.specialAlaioStrike,
        sound: 'special-alaio-strike',
      },
    },
    sprite: {
      sheet: {
        key: 'dmitry-sheet',
        path: 'fighters/dmitry/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // Eight transparent pixels below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
        // ALAIO STRIKE!: guard up, then the fist raised to the sky (frame 40) until it ends.
        special: { frames: [14, 40, 40], attackPhases: { startup: 1, active: 1, recovery: 1 } },
      },
    },
  },
};
