import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/** Technical mid-range fighter: reach trades startup and recovery for spacing. */
export const filipe: FighterConfig = {
  id: 'filipe',
  name: 'filipe',
  displayName: 'FILIPE',
  description: 'Arrecife Digital',
  selectable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.25,
    backWalkSpeed: 2.65,
    jumpForce: 16.5,
    jumpHorizontalSpeed: 4.0,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'filipe.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 7,
      chipDamage: 0,
      startupFrames: 6,
      activeFrames: 3,
      recoveryFrames: 10,
      hitbox: { x: 24, y: -142, width: 62, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'filipe.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 10,
      chipDamage: 1,
      startupFrames: 11,
      activeFrames: 4,
      recoveryFrames: 18,
      hitbox: { x: 30, y: -100, width: 80, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    // Crouching attacks (↓ + A / ↓ + S): the fighter stays low and uses the crouching hurtbox.
    crouchPunch: {
      id: 'filipe.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      // Hits the torso (y -92..-70): blockable either way once levels exist, so 'mid'.
      level: 'mid',
      damage: 5,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 3,
      recoveryFrames: 9,
      hitbox: { x: 22, y: -92, width: 56, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'filipe.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      // Sweeps the shins, long and low.
      level: 'low',
      damage: 8,
      chipDamage: 1,
      startupFrames: 10,
      activeFrames: 4,
      recoveryFrames: 20,
      hitbox: { x: 26, y: -28, width: 94, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    // Air attacks: gravity and jump momentum continue; they end on landing.
    airPunch: {
      id: 'filipe.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 6,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 6,
      recoveryFrames: 10,
      // Chest height, medium reach: connects on the way down.
      hitbox: { x: 16, y: -118, width: 58, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'filipe.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 9,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 8,
      recoveryFrames: 15,
      // Long, angled down and starting slightly behind the body: hits cross-ups.
      hitbox: { x: -12, y: -80, width: 96, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [],
  palette: { body: 0x153869, accent: 0x25bad0, skin: 0xb57952, outline: 0x080b12 },
  assets: {
    portrait: 'fighters/filipe/portrait.png',
    pixelArt: true,
    sprite: {
      sheet: {
        key: 'filipe-sheet',
        path: 'fighters/filipe/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // The atlas keeps an eight-pixel transparent margin below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
      },
    },
  },
};
