import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/** Quick normals trade damage for mobility, with punishable recovery. */
export const gabrielMattozo: FighterConfig = {
  id: 'gabriel-mattozo',
  name: 'gabriel-mattozo',
  displayName: 'GABRIEL MATTOZO',
  description: 'GMC',
  playable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.4,
    backWalkSpeed: 2.8,
    jumpForce: 16.8,
    jumpHorizontalSpeed: 4.1,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'gabriel-mattozo.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 6,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 10,
      hitbox: { x: 24, y: -142, width: 58, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'gabriel-mattozo.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 10,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 16,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    crouchPunch: {
      id: 'gabriel-mattozo.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 5,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 9,
      hitbox: { x: 22, y: -92, width: 52, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'gabriel-mattozo.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 9,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 4,
      recoveryFrames: 17,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    airPunch: {
      id: 'gabriel-mattozo.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 6,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 6,
      recoveryFrames: 10,
      hitbox: { x: 16, y: -118, width: 52, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'gabriel-mattozo.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 9,
      chipDamage: 1,
      startupFrames: 7,
      activeFrames: 8,
      recoveryFrames: 13,
      hitbox: { x: -12, y: -80, width: 90, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [],
  palette: { body: 0xd9c8aa, accent: 0x4f88c6, skin: 0xd49a73, outline: 0x0b0820 },
  assets: {
    portrait: 'fighters/gabriel-mattozo/portrait.png',
    pixelArt: true,
    sprite: {
      sheet: {
        key: 'gabriel-mattozo-sheet',
        path: 'fighters/gabriel-mattozo/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // Eight transparent pixels below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
      },
    },
  },
};
