import { STRINGS } from '../config/strings';
import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/** Quick normals trade damage for mobility, with punishable recovery. */
export const gabriele: FighterConfig = {
  id: 'gabriele',
  name: 'gabriele',
  displayName: 'GABRIELE',
  description: 'Inovar Consulting',
  playable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.25,
    backWalkSpeed: 2.55,
    jumpForce: 16.5,
    jumpHorizontalSpeed: 3.9,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      id: 'gabriele.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 7,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 11,
      hitbox: { x: 24, y: -142, width: 58, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'gabriele.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 10,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 17,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    crouchPunch: {
      id: 'gabriele.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 5,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 9,
      hitbox: { x: 22, y: -92, width: 52, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'gabriele.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 9,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 18,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    airPunch: {
      id: 'gabriele.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 6,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 6,
      recoveryFrames: 10,
      hitbox: { x: 16, y: -118, width: 52, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'gabriele.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 10,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 8,
      recoveryFrames: 14,
      hitbox: { x: -12, y: -80, width: 90, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [
    {
      // CHAMA O 190!: she calls the police and a patrol car fires a volley at the rival (cartoon).
      // The longest reach in the cast, paid for with a slow call and a long recovery.
      id: 'gabriele.190',
      displayName: STRINGS.specialPolice,
      state: 'special',
      level: 'mid',
      meterCost: 40,
      groundOnly: true,
      // She stays put while the car pulls up behind her.
      advanceSpeed: 0,
      damage: 18,
      chipDamage: 3,
      // The car has to arrive: easy to see coming.
      startupFrames: 18,
      activeFrames: 9,
      // Very punishable when blocked (26 recovery against 14 blockstun).
      recoveryFrames: 26,
      // The volley's reach: 280 px (N8N!: 176; her kick: ~100).
      hitbox: { x: 30, y: -136, width: 250, height: 74 },
      hitstunFrames: 24,
      blockstunFrames: 14,
      knockback: 9,
      blockPushback: 6,
      hitstopFrames: 12,
    },
  ],
  palette: { body: 0xf0d3ad, accent: 0xd90835, skin: 0xd99b77, outline: 0x0b0820 },
  assets: {
    specialEffects: {
      'gabriele.190': {
        style: 'policeRaid',
        emblem: 'vfx/police-car.png',
        label: STRINGS.specialPolice,
        sound: 'special-190',
      },
    },
    portrait: 'fighters/gabriele/portrait.png',
    pixelArt: true,
    sprite: {
      sheet: {
        key: 'gabriele-sheet',
        path: 'fighters/gabriele/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // Eight transparent pixels below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
        // CHAMA O 190!: hand up (the call), then pointing the police at the rival.
        special: { frames: [39, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
      },
    },
  },
};
