import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/**
 * JOÃO GUIOTTI - São Paulo, SP. Technical and balanced: good walk speed, the quickest jab,
 * medium reach. First rival of the Partner Tour story campaign.
 * No art yet: drawn by the generic placeholder renderer (figure and portrait) in its own
 * palette. Adding art later is only `assets` (see docs/ART_DIRECTION.md).
 */
export const joaoGuiotti: FighterConfig = {
  id: 'joao-guiotti',
  name: 'joao_guiotti',
  displayName: 'JOÃO GUIOTTI',
  description: 'São Paulo - SP',
  selectable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 3.3,
    backWalkSpeed: 2.7,
    jumpForce: 16.8,
    jumpHorizontalSpeed: 4.1,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      // Quick jab, the best starter of the roster.
      id: 'joao-guiotti.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 6,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 9,
      hitbox: { x: 24, y: -142, width: 58, height: 22 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    kick: {
      id: 'joao-guiotti.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 10,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 4,
      recoveryFrames: 15,
      hitbox: { x: 30, y: -100, width: 70, height: 30 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    crouchPunch: {
      id: 'joao-guiotti.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 5,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 3,
      recoveryFrames: 7,
      hitbox: { x: 22, y: -92, width: 52, height: 22 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3,
      blockPushback: 2.5,
      hitstopFrames: 5,
    },
    crouchKick: {
      id: 'joao-guiotti.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 8,
      chipDamage: 1,
      startupFrames: 8,
      activeFrames: 4,
      recoveryFrames: 16,
      hitbox: { x: 26, y: -28, width: 86, height: 24 },
      hitstunFrames: 16,
      blockstunFrames: 11,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 7,
    },
    airPunch: {
      id: 'joao-guiotti.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 6,
      chipDamage: 0,
      startupFrames: 4,
      activeFrames: 6,
      recoveryFrames: 8,
      hitbox: { x: 16, y: -118, width: 52, height: 28 },
      hitstunFrames: 14,
      blockstunFrames: 9,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    airKick: {
      id: 'joao-guiotti.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 9,
      chipDamage: 1,
      startupFrames: 7,
      activeFrames: 8,
      recoveryFrames: 12,
      hitbox: { x: -12, y: -80, width: 90, height: 36 },
      hitstunFrames: 17,
      blockstunFrames: 12,
      knockback: 5,
      blockPushback: 4,
      hitstopFrames: 8,
    },
  },
  specials: [],
  palette: { body: 0x7b2cbf, accent: 0x2fe0ff, skin: 0xe0ac69, outline: 0x0b0820 },
  assets: {},
};
