import type { FighterConfig } from '../types/fighter';
import { STANDARD_BODY } from './shared/standardBody';

/**
 * ROMUALDO - Joinville, SC. A bit heavier: walks a little slower and hits harder, paying with
 * longer recoveries. Final rival of the Partner Tour story campaign.
 * Original artwork is independent from combat timing and geometry.
 */
export const romualdo: FighterConfig = {
  id: 'romualdo',
  name: 'romualdo',
  displayName: 'ROMUALDO',
  description: 'Joinville - SC',
  playable: true,
  stats: {
    maxHealth: 100,
    walkSpeed: 2.85,
    backWalkSpeed: 2.3,
    jumpForce: 16.2,
    jumpHorizontalSpeed: 3.7,
  },
  boxes: STANDARD_BODY,
  attacks: {
    punch: {
      // Heavier hands: more damage, slower recovery.
      id: 'romualdo.punch',
      displayName: 'Soco',
      state: 'punch',
      level: 'high',
      damage: 8,
      chipDamage: 0,
      startupFrames: 6,
      activeFrames: 3,
      recoveryFrames: 12,
      hitbox: { x: 24, y: -142, width: 56, height: 24 },
      hitstunFrames: 15,
      blockstunFrames: 9,
      knockback: 4.5,
      blockPushback: 3.5,
      hitstopFrames: 7,
    },
    kick: {
      id: 'romualdo.kick',
      displayName: 'Chute',
      state: 'kick',
      level: 'mid',
      damage: 13,
      chipDamage: 1,
      startupFrames: 11,
      activeFrames: 4,
      recoveryFrames: 19,
      hitbox: { x: 30, y: -100, width: 68, height: 30 },
      hitstunFrames: 19,
      blockstunFrames: 12,
      knockback: 7,
      blockPushback: 5,
      hitstopFrames: 9,
    },
    crouchPunch: {
      id: 'romualdo.crouchPunch',
      displayName: 'Soco agachado',
      state: 'crouchPunch',
      level: 'mid',
      damage: 6,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 3,
      recoveryFrames: 10,
      hitbox: { x: 22, y: -92, width: 50, height: 24 },
      hitstunFrames: 13,
      blockstunFrames: 8,
      knockback: 3.5,
      blockPushback: 3,
      hitstopFrames: 6,
    },
    crouchKick: {
      id: 'romualdo.crouchKick',
      displayName: 'Rasteira',
      state: 'crouchKick',
      level: 'low',
      damage: 11,
      chipDamage: 1,
      startupFrames: 10,
      activeFrames: 4,
      recoveryFrames: 20,
      hitbox: { x: 26, y: -28, width: 84, height: 24 },
      hitstunFrames: 17,
      blockstunFrames: 11,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 8,
    },
    airPunch: {
      id: 'romualdo.airPunch',
      displayName: 'Soco aéreo',
      state: 'airPunch',
      level: 'overhead',
      damage: 8,
      chipDamage: 0,
      startupFrames: 5,
      activeFrames: 5,
      recoveryFrames: 10,
      hitbox: { x: 16, y: -118, width: 52, height: 30 },
      hitstunFrames: 15,
      blockstunFrames: 9,
      knockback: 4,
      blockPushback: 3.5,
      hitstopFrames: 7,
    },
    airKick: {
      id: 'romualdo.airKick',
      displayName: 'Chute aéreo',
      state: 'airKick',
      level: 'overhead',
      damage: 12,
      chipDamage: 1,
      startupFrames: 9,
      activeFrames: 8,
      recoveryFrames: 15,
      hitbox: { x: -12, y: -80, width: 88, height: 36 },
      hitstunFrames: 18,
      blockstunFrames: 12,
      knockback: 6,
      blockPushback: 4.5,
      hitstopFrames: 9,
    },
  },
  specials: [],
  palette: { body: 0x2e8b57, accent: 0xff8a1f, skin: 0xc68642, outline: 0x0b0820 },
  assets: {
    portrait: 'fighters/romualdo/portrait.png',
    pixelArt: true,
    sprite: {
      sheet: {
        key: 'romualdo-sheet',
        path: 'fighters/romualdo/sprite.png',
        frameWidth: 192,
        frameHeight: 224,
      },
      // Eight transparent pixels below the grounded soles.
      visual: { scale: 1, offsetX: 0, offsetY: 8 },
      animations: {
        idle: { frames: [0, 1, 2, 3], frameRate: 6 },
        walk: { frames: [4, 5, 6, 7, 8, 9], frameRate: 10 },
        jump: { frames: [10, 11, 12], jumpPhases: { rise: 1, apex: 1, fall: 1 } },
        crouch: { frames: [13] },
        punch: { frames: [14, 15, 16], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        kick: { frames: [17, 18, 19], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchPunch: { frames: [20, 21, 22], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        crouchKick: { frames: [23, 24, 25], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airPunch: { frames: [26, 27, 28], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        airKick: { frames: [29, 30, 31], attackPhases: { startup: 1, active: 1, recovery: 1 } },
        block: { frames: [32] },
        crouchBlock: { frames: [33] },
        hurt: { frames: [34, 35], frameRate: 10 },
        knockout: { frames: [36, 37, 38], frameRate: 8 },
        victory: { frames: [39] },
      },
    },
  },
};
